### ISSUE TITLE
Improve sublayers

### ISSUE THREAD

**Issue by macmv** [macmv/rgen#23]
Currently, sublayers are only a single block state, and they can be 2 to 5 blocks deep, depending on a global noisemap. Here is a redesign of the sublayer system to fix the following issues:
- River beds have a stone floor. They should have a gravel floor, which should be generated the same way as other sublayers (with some special casing to treat all the water as the top layer).
- Deserts should have multiple sand blocks on the top, as well as a thicker sandstone layer than the dirt layer in other biomes.
- The sand from beaches currently extends underwater. We do not want sand underwater, we want other, customizable layers instead.

Unresolved issues:
- Mesa biomes have fixed height sublayers, which results in horizontal lines that intersperse through mountains. This requires a new system that is unrelated to sublayers in all other biomes.

## Design

This requires the following changes to the `BiomeBuilder`:

```rs
struct BiomeBuilder {
  ...
  // Replace `top_layer` and `sub_layer` with:
  layers: Vec<Layer>,
  underwater_layers: Vec<Layer>,
  ...
}

struct Layer {
  state: BlockState,
  min_height: u32,
  max_height: u32,
}
```

Layers will be defined top to bottom, so the first element of the `layers` array will be the top block of the biome.

Because these layers will be defined in an array, we will add some helper functions to `BiomeBuilder`:
```rs
// Instead of setting the top layer, with
gen.top_block = ctx.blocks.grass;
// The new code will require
gen.top_block(ctx.blocks.grass);

// Instead of setting the sub_layer, with
gen.sub_layer = ctx.blocks.dirt;
// The new code will require
gen.add_layer(ctx.blocks.dirt, 2, 5);
```

The `BiomeBuilder::top_block` function will assert that no previous layers have been declared, and then insert a one-block tall layer. The `BiomeBuilder::add_layer` function will append a layer to the list. So, calling it multiple times will add layers further below the surface.

The current sublayer depth map will be used to determine each layer's width at each XZ coordinate. For each layer, the XZ coordinate will be offset by a predetermined value, so that the layers can change height independant of each other.

As a special case, if the `min_height` and `max_height` are the same, then that height will be used (the noise map will not be sampled). This allows a single block layer to be spread consistently over the terrain.

This first pass will not attempt to resolve biome borders. Because layers are underground, we can have a sharp edge between biomes like deserts and savannas.

**Comment by JaimieGR** [comment]
This makes a lot of sense; however, I don't believe this will fix rivers and will, in fact, cause more problems because the sides of the river (river bank) can stretch up to 5 blocks away and is a different biome. The blocks below the river bank should function like the river bank biome rather than be clay and gravel.

**Comment by macmv** [comment]
Alrighty, we'll add a second `underwater_layers` array to `BiomeBuilder`, which will be sampled instead of `layers` when underwater. This'll also fix the beach sand showing up underwater.
