### ISSUE TITLE
Color overload

### ISSUE THREAD

**Issue by JaimieGR** [macmv/rgen#8]
This error seems to occur when RGB values of height color and the biome color are greater than 255 and cause the program to panic at either lines 174,175, or 176 of the rgen-viewer main

this is the error code that is outputted

`thread 'main' panicked at rgen-viewer/src/main.rs:175:17:
attempt to add with overflow
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace`

Currently I've commented out the offending code to only show height_color

**Comment by macmv** [comment]
this is fixed
